### ISSUE TITLE
[Bug] Llama3 Chat Template are not consistency with the Huggingface implementation. 

### ISSUE THREAD

**Issue by efsotr** [InternLM/lmdeploy#1945]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Llama3 Chat Template are not consistency with the Huggingface implementation. 

Here is a reference to the relevant code:
https://github.com/InternLM/lmdeploy/blob/ab5b7ce3820b1cb4a999895991e57cd570103f11/lmdeploy/model.py#L798-L802

The addition of "[:-1]" at the end of the prompt removes the '\n' character.

### Reproduction

```python
conversation = [{"role": "user", "content": "Are you ok?"}]

from transformers import AutoTokenizer
t = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")
print(repr(t.apply_chat_template(conversation, tokenize=False, add_generation_prompt=True)))

from lmdeploy.model import Llama3
t = Llama3(model_name='llama', capability='completion')
print(repr(t.messages2prompt(conversation)))
```

stdout
```
'<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nAre you ok?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'
'<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nAre you ok?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
```

### Environment

```Shell
x
```

**Comment by zhyncs** [comment]
The question is very interesting. My response may not be directly related to the question itself, but I can share our internal approach. Because we are using a SOTA model for SFT, when performing SFT, the prompt used is manually concatenated based on our own rules. It has some differences from the chat template in LMDeploy. In fact, we don't use the built-in chat template of LMDeploy online either. Instead, we disable the chat template by setting `do_preprocess=False` and concatenate templates on the client side.

**Comment by lvhan028** [comment]
It has been resolved in the latest main branch
