### ISSUE TITLE
pipeline inference bug

### ISSUE THREAD

**Issue by nzomi** [InternLM/lmdeploy#2225]
Hello Developers,

I've encountered a bug where inference for InternLM-XComposer2-4kHD using the pipeline works correctly only with lmdeploy==0.5.0. Higher versions produce unexpected outputs with the same fine-tuned model. Could you please look into this?

**Comment by irexyc** [comment]
Does the logger prints same `prompt_token_id` when you using different versions of lmdeploy and setting the log level to INFO ?

**Comment by nzomi** [comment]
@irexyc Completely different, I put some screenshot for your reference, the later is normal result.
![image](https://github.com/user-attachments/assets/499e3886-7f28-4b6b-b601-7ea5c4d1b8dd)
![image](https://github.com/user-attachments/assets/c9b2bdc7-8ca8-4e49-ae59-53d6868e9d01)

**Comment by irexyc** [comment]
With the `prompt_token_id` in your log, I think the problem is the first doesn't match the right chat template.

Lmdeploy use the folder name to match template by default, I'm not sure if it is related the change of matching rules.

You can try initialize the pipeline by specifically setting the  `chat_template_config`
```
pipeline(..., chat_template_config=ChatTemplateConfig('internlm-xcomposer2'))
```

**Comment by nzomi** [comment]
@irexyc Thank you for your solution; it indeed fixed the issue. Version 0.5.0 supports the chat template 'internlm-xcomposer2-4khd', while later versions should use 'internlm-xcomposer'.
