### ISSUE TITLE
[Feature] Qwen-VL-72B-Instruct 

### ISSUE THREAD

**Issue by yeonggon** [InternLM/lmdeploy#2503]
### Motivation

I was noticed that new version released that supporting qwen vl 2B an d 7B.
Do you have plan to release another param Qwen-VL-72B ?
If so could you share the release date ?

**Comment by irexyc** [comment]
I compared the config of Qwen2-VL-72B-Instruct and Qwen2-VL-7B-Instruct and it seems only some layer's settings are different, so I think the current code should support Qwen2-VL-72B-Instruct.

The current code only support inference this model with half/bfloat16 dtype in pytorch backend. Since this model is very big, it may need large cuda memory. And the awq model with turbomind backend support may be released next month.
