### ISSUE TITLE
[Question] About the meaning of `permute_v2` function at weight loading 

### ISSUE THREAD

**Issue by vicety** [InternLM/lmdeploy#2639]
Hi, 

I just started reading the source code of the weight loading part, specifically in `lmdeploy/turbomind/deploy/exporter.py`, within the `export_attn` function. I'm struggling to understand a couple of things:

1. Why `permute_qk` is default True, and why does it only call `permute_v2` for `q` and `k`, but not for `v`?
2. What is `permute_v2` trying to do? `x.view(-1, head_num, 2,size_per_head // 2).transpose(2, 3).reshape(x.shape)` is really confusing.

Any insights would be greatly appreciated!

**Comment by lvhan028** [comment]
huggingface permute q, k when converting meta llama weight so that the rotary embedding can be calculated by:
```python
def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)
 cos = cos.unsqueeze(unsqueeze_dim)
  sin = sin.unsqueeze(unsqueeze_dim)
  q_embed = (q * cos) + (rotate_half(q) * sin)
  k_embed = (k * cos) + (rotate_half(k) * sin)
```
Pay attention to `rotate_half`

turbomind implements llama based on meta llama weight, instead of huggingface llama model weight
So turbomind needs to permute huggingface llama back to meta llama weight. That's why `permute_qk` is True by default

The reason why turbomind didn't follow huggingface llama because we start the project before huggingface release its converted llama model

**Comment by lzhangzz** [comment]
If you see RoPE as rotations on (x, y) pairs, most models in transformers is
```
x_0, x_1, x_2, ... , x_d/2-1, y_0, y_1, y_2, ..., y_d/2-1
```
what turbomind's kernel uses
```
x_0, y_0, x_1, y_1, x_2, y_2, ..., x_d/2-1, y_d/2-1
```
