### ISSUE TITLE
[Question] Is there any hidden limitation of max_batch_size? 

### ISSUE THREAD

**Issue by realgump** [InternLM/lmdeploy#270]
I use both the w4a16 and kv_int8 to inference my vicuna13b model on A100-80g, and set the `config.ini` as following:
```
[llama]
model_name = vicuna
head_num = 40
kv_head_num = 40
size_per_head = 128
vocab_size = 32000
num_layer = 40
rotary_embedding = 128
inter_size = 13824
norm_eps = 1e-06
attn_bias = 0
start_id = 1
end_id = 2
weight_type = int4
group_size = 128
max_batch_size = 128
max_context_token_num = 4
session_len = 2056
step_length = 1
cache_max_entry_count = 48
cache_chunk_size = 1
use_context_fmha = 0
quant_policy = 4
tensor_para_size = 1
```
As the client concurrency increases, the runtime batch size equals the concurrency when the concurrency is less than or equal to 32. However, when the concurrency exceeds 32, the runtime batch size remains fixed at 32, regardless of further increases in concurrency. 
I am puzzled as to whether there are any hidden limitations to the max_batch_size setting, or if there are any mistakes in my configuration?

**Comment by lzhangzz** [comment]
There is no hidden limitation on max batch size. And it's strange that your modification of `max_batch_size` didn't take effect.

However, `cache_max_entry_count` should be greater or equal to `max_batch_size`. It's the max number of sequences the cache manager holds. If the runtime batch size exceeds `cache_max_entry_count`, your process will likely to crash due to checks in the code.

**Comment by realgump** [comment]
It find out the max_concurrency here is set to 32 for me.
https://github.com/InternLM/lmdeploy/blob/eb3b4dc910305f71257b97fca31a81323dd8ba81/lmdeploy/serve/turbomind/triton_models/interactive/config.pbtxt#L36-L42
