### ISSUE TITLE
怎么用OpenCompas 测试 kvcache 量化的的精度

### ISSUE THREAD

**Issue by seeyourcell** [InternLM/lmdeploy#608]
### Motivation

怎么用OpenCompas 测试 kvcache 量化的的精度

**Comment by lin65505578** [comment]
有对应的脚本吗？ 在OpenCompass 看到可以用 huggface 的模型测试，但kvcache 量化的模型怎么用 OpenCompass 测试

**Comment by lvhan028** [comment]
opencompass中有一个PR：
https://github.com/open-compass/opencompass/pull/484
只要准备好 kv cache 量化后的 turbomind 模型，就能使用这个PR测试了。
不过这个PR中的config是针对 internlm 模型的。

**Comment by lin65505578** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/12838445/dc0adf07-3f1e-4378-b11d-8c9cbb8b7737)

1、只要准备好 kv cache 量化后的 turbomind 模型  的路径，选择  ./workspace  还是workspace/turbomind  还是 workspace/triton_models
2、 triton_models    和 turbomind 有什么区别， 开启kv cache 量化 是 triton_models的weight 还是   turbomind/1/weight

**Comment by lvhan028** [comment]
Since v0.4.0, LMDeploy has supported online 4-bit/8-bit kv cache quantization. The old offline way was removed.
The guide about the model evaluation using lmdeploy as an accelerator can be found from [here](https://lmdeploy.readthedocs.io/en/latest/benchmark/evaluate_with_opencompass.html)

If kv cache quantization is required for evaluation, please set `quant_policy` to the `engine_config`. `quant_policy=4` means 4-bit kv quantization and `quant_policy=8` indicates 8-bit kv quantization
